name: dio_prac
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  shared_preferences: ^2.5.3
  permission_handler: ^11.3.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  pinch_zoom: ^2.0.0
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/


flutter_icons:
  android: true
  ios: true
  image_path: assets/images/img_Ecommerce_logo.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFE0B2"
  image: assets/lottie/img_Ecommerce_logo_big.png

  android_12:
    color: "#FFE0B2"
    image: assets/images/img_Ecommerce_logo_big.png

  ios: true
  android: true



