name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  shared_preferences: ^2.5.3
  permission_handler: ^11.3.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  pinch_zoom: ^2.0.0
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/icons/


# flutter_native_splash:
#   # color: "#FF9900"
#   image : assets/images/img_ecommerce_big.jpg
#   background_image_android: assets/images/splash_background.jpg
#   background_image_dark_android: assets/images/splash_background.jpg

#   background_image_web: assets/images/splash_background.jpg

#   android_12:
#     color: "#FF9900"
#     image: assets/images/img_ecommerce_big.jpg
#     branding : assets/images/img_brandin2.jpg
#     branding_dark : assets/images/img_brandin2.jpg
#     # background_image_android: assets/images/splash_background.jpg
#     # background_image_dark_android: assets/images/splash_background.jpg

#   android : true




